language: php
php:
  - '7.2'
  - '8.0'

install:
    - composer self-update
    - composer install

script: composer test -- --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.composer/cache

